import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:http/http.dart' as http;
import 'package:supabase_flutter/supabase_flutter.dart';
import '../domain/sale_record_model.dart';
import '../data/sales_repository.dart';
import '../../auth/domain/profile_model.dart';
import '../../settings/presentation/settings_provider.dart';
import '../../../dashboard_provider.dart';

final salesRepositoryProvider = Provider<SalesRepository>((ref) => SalesRepository());

class SalesHistoryPage extends ConsumerStatefulWidget {
  const SalesHistoryPage({super.key});

  @override
  ConsumerState<SalesHistoryPage> createState() => _SalesHistoryPageState();
}

class _SalesHistoryPageState extends ConsumerState<SalesHistoryPage> {
  DateTime? _startDate;
  DateTime? _endDate;
  String? _filterUserId;
  List<SaleRecordModel> _sales = [];
  List<ProfileModel> _users = [];
  bool _loading = true;
  bool _loadingUsers = true;

  @override
  void initState() {
    super.initState();
    _loadUsers();
    _loadSales();
  }

  Future<void> _loadUsers() async {
    setState(() => _loadingUsers = true);
    try {
      final res = await Supabase.instance.client.from('profiles').select().order('full_name');
      setState(() {
        _users = (res as List).map((e) => ProfileModel.fromJson(Map<String, dynamic>.from(e))).toList();
        _loadingUsers = false;
      });
    } catch (_) {
      setState(() => _loadingUsers = false);
    }
  }

  Future<void> _loadSales() async {
    setState(() => _loading = true);
    try {
      final repo = ref.read(salesRepositoryProvider);
      final list = await repo.getSales(
        startDate: _startDate,
        endDate: _endDate,
        createdBy: _filterUserId,
      );
      setState(() {
        _sales = list;
        _loading = false;
      });
    } catch (_) {
      setState(() => _loading = false);
    }
  }

  Future<void> _exportPdf() async {
    final settings = await ref.read(settingsProvider.future);
    final profile = await ref.read(profileProvider.future);
    final generatorName = profile?.fullName ?? Supabase.instance.client.auth.currentUser?.email ?? 'System';

    Uint8List? logoBytes;
    if (settings.logoUrl.isNotEmpty) {
      try {
        final res = await http.get(Uri.parse(settings.logoUrl));
        if (res.statusCode == 200) logoBytes = res.bodyBytes;
      } catch (_) {}
    }

    final doc = pw.Document();
    final dateFormat = DateFormat('yyyy-MM-dd HH:mm');
    final total = _sales.fold<double>(0, (s, e) => s + e.totalAmount);
    final periodText = 'Period: ${_startDate != null ? DateFormat('yyyy-MM-dd').format(_startDate!) : 'Any'} - ${_endDate != null ? DateFormat('yyyy-MM-dd').format(_endDate!) : 'Any'}';
    final isThermal = settings.printerType == 'thermal';
    final pageFormat = isThermal ? const PdfPageFormat(227, 800, marginAll: 12) : PdfPageFormat.a4;

    doc.addPage(
      pw.MultiPage(
        pageFormat: pageFormat,
        margin: isThermal ? const pw.EdgeInsets.all(12) : const pw.EdgeInsets.all(24),
        header: (context) => pw.SizedBox.shrink(),
        footer: (context) => pw.Padding(
          padding: const pw.EdgeInsets.only(top: 12),
          child: pw.Text(
            'Generated by $generatorName on ${dateFormat.format(DateTime.now())}',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
          ),
        ),
        build: (context) => [
          if (logoBytes != null)
            pw.Center(
              child: pw.Container(
                height: 50,
                margin: const pw.EdgeInsets.only(bottom: 12),
                child: pw.Image(pw.MemoryImage(logoBytes), fit: pw.BoxFit.contain),
              ),
            ),
          pw.Center(
            child: pw.Column(
              mainAxisSize: pw.MainAxisSize.min,
              children: [
                pw.Text(
                  settings.shopName.isNotEmpty ? settings.shopName : 'Sales Report',
                  style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 4),
                if (settings.poBox.isNotEmpty)
                  pw.Text(
                    'P.O. Box: ${settings.poBox}',
                    style: const pw.TextStyle(fontSize: 9),
                    textAlign: pw.TextAlign.center,
                  ),
                if (settings.address.isNotEmpty)
                  pw.Text(
                    'Address: ${settings.address}',
                    style: const pw.TextStyle(fontSize: 9),
                    textAlign: pw.TextAlign.center,
                  ),
                if (settings.phoneNumber.isNotEmpty)
                  pw.Text(
                    'Tel: ${settings.phoneNumber}',
                    style: const pw.TextStyle(fontSize: 9),
                    textAlign: pw.TextAlign.center,
                  ),
              ],
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text('Sales Report', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.Text(periodText, style: const pw.TextStyle(fontSize: 10)),
          pw.SizedBox(height: 16),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
            columnWidths: const {
              0: pw.FlexColumnWidth(2),
              1: pw.FlexColumnWidth(2),
              2: pw.FlexColumnWidth(1.2),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                children: [
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text('Date', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text('Seller', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text('Amount', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  ),
                ],
              ),
              ..._sales.map(
                (s) => pw.TableRow(
                  children: [
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(dateFormat.format(s.createdAt), style: const pw.TextStyle(fontSize: 10)),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(s.sellerName ?? '-', style: const pw.TextStyle(fontSize: 10)),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text('\$${s.totalAmount.toStringAsFixed(2)}', style: const pw.TextStyle(fontSize: 10)),
                    ),
                  ],
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              'Total: \$${total.toStringAsFixed(2)}',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => doc.save(),
      name: 'Sales_Report_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.pdf',
    );
  }

  Future<void> _printReport() async {
    await _exportPdf();
  }

  Future<void> _showSaleItems(BuildContext context, SaleRecordModel sale, ColorScheme colorScheme) async {
    final repo = ref.read(salesRepositoryProvider);
    final items = await repo.getSaleItems(sale.id);
    if (!context.mounted) return;
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: colorScheme.surface,
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))),
      builder: (context) => DraggableScrollableSheet(
        initialChildSize: 0.6,
        minChildSize: 0.3,
        maxChildSize: 0.95,
        expand: false,
        builder: (context, scrollController) => Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const SizedBox(height: 8),
            Container(width: 40, height: 4, decoration: BoxDecoration(color: colorScheme.onSurfaceVariant.withAlpha(102), borderRadius: BorderRadius.circular(2))),
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 16, 20, 8),
              child: Row(
                children: [
                  Text('Products sold', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700, color: colorScheme.onSurface)),
                  const Spacer(),
                  Text('\$${sale.totalAmount.toStringAsFixed(2)}', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: colorScheme.primary)),
                ],
              ),
            ),
            Flexible(
              child: items.isEmpty
                  ? Center(child: Text('No line items recorded for this sale.', style: TextStyle(color: colorScheme.onSurfaceVariant)))
                  : ListView.builder(
                      controller: scrollController,
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 24),
                      itemCount: items.length,
                      itemBuilder: (context, index) {
                        final i = items[index];
                        return Padding(
                          padding: const EdgeInsets.only(bottom: 10),
                          child: Material(
                            color: colorScheme.surfaceContainerHighest.withAlpha(60),
                            borderRadius: BorderRadius.circular(14),
                            child: ListTile(
                              contentPadding: const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
                              leading: ClipRRect(
                                borderRadius: BorderRadius.circular(10),
                                child: i.imageUrl.isNotEmpty
                                    ? Image.network(
                                        i.imageUrl,
                                        width: 52,
                                        height: 52,
                                        fit: BoxFit.cover,
                                        errorBuilder: (_, __, ___) => Container(
                                          width: 52,
                                          height: 52,
                                          color: colorScheme.primaryContainer.withAlpha(80),
                                          child: Icon(Icons.inventory_2_rounded, color: colorScheme.primary, size: 26),
                                        ),
                                      )
                                    : Container(
                                        width: 52,
                                        height: 52,
                                        color: colorScheme.primaryContainer.withAlpha(80),
                                        child: Icon(Icons.inventory_2_rounded, color: colorScheme.primary, size: 26),
                                      ),
                              ),
                              title: Text(i.productName, style: TextStyle(fontWeight: FontWeight.w600, color: colorScheme.onSurface)),
                              subtitle: Text('Qty: ${i.quantity} × \$${i.unitPrice.toStringAsFixed(2)}', style: TextStyle(color: colorScheme.onSurfaceVariant, fontSize: 12)),
                              trailing: Text('\$${i.totalPrice.toStringAsFixed(2)}', style: TextStyle(fontWeight: FontWeight.w700, color: colorScheme.primary)),
                            ),
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final dateFormat = DateFormat('MMM d, y HH:mm');

    return Scaffold(
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Text('Sales History', style: TextStyle(fontWeight: FontWeight.w700, color: colorScheme.onSurface)),
        leading: IconButton(
          icon: Icon(Icons.arrow_back_rounded, color: colorScheme.onSurface),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          if (_sales.isNotEmpty) ...[
            IconButton(
              icon: Icon(Icons.picture_as_pdf_rounded, color: colorScheme.primary),
              onPressed: _exportPdf,
              tooltip: 'Export PDF',
            ),
            IconButton(
              icon: Icon(Icons.print_rounded, color: colorScheme.primary),
              onPressed: _printReport,
              tooltip: 'Print',
            ),
          ],
        ],
      ),
      body: Column(
        children: [
          // Filters — responsive padding for landscape
          Padding(
            padding: EdgeInsets.fromLTRB(
              MediaQuery.orientationOf(context) == Orientation.landscape ? 8 : 16,
              12,
              MediaQuery.orientationOf(context) == Orientation.landscape ? 8 : 16,
              8,
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Expanded(
                      child: OutlinedButton.icon(
                        onPressed: () async {
                          final date = await showDatePicker(
                            context: context,
                            initialDate: _startDate ?? DateTime.now(),
                            firstDate: DateTime(2020),
                            lastDate: DateTime.now(),
                          );
                          if (date != null) setState(() => _startDate = date);
                          _loadSales();
                        },
                        icon: const Icon(Icons.calendar_today_rounded, size: 18),
                        label: Text(_startDate != null ? DateFormat('MMM d').format(_startDate!) : 'Start'),
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: OutlinedButton.icon(
                        onPressed: () async {
                          final date = await showDatePicker(
                            context: context,
                            initialDate: _endDate ?? DateTime.now(),
                            firstDate: _startDate ?? DateTime(2020),
                            lastDate: DateTime.now(),
                          );
                          if (date != null) setState(() => _endDate = date);
                          _loadSales();
                        },
                        icon: const Icon(Icons.calendar_today_rounded, size: 18),
                        label: Text(_endDate != null ? DateFormat('MMM d').format(_endDate!) : 'End'),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                if (_loadingUsers)
                  const SizedBox(height: 40, child: Center(child: CircularProgressIndicator(strokeWidth: 2)))
                else
                  DropdownButtonFormField<String?>(
                    value: _filterUserId,
                    decoration: InputDecoration(
                      labelText: 'Filter by user',
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                      isDense: true,
                    ),
                    items: [
                      const DropdownMenuItem(value: null, child: Text('All users')),
                      ..._users.map(
                        (u) => DropdownMenuItem(
                          value: u.id,
                          child: Text('${u.fullName} (${u.role})'),
                        ),
                      ),
                    ],
                    onChanged: (v) {
                      setState(() => _filterUserId = v);
                      _loadSales();
                    },
                  ),
              ],
            ),
          ),
          // List
          Expanded(
            child: _loading
                ? Center(child: CircularProgressIndicator(color: colorScheme.primary))
                : _sales.isEmpty
                    ? Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(Icons.receipt_long_rounded, size: 64, color: colorScheme.onSurfaceVariant.withAlpha(120)),
                            const SizedBox(height: 16),
                            Text(
                              'No sales in this period',
                              style: TextStyle(color: colorScheme.onSurfaceVariant, fontSize: 16),
                            ),
                          ],
                        ),
                      )
                    : ListView.builder(
                        padding: EdgeInsets.symmetric(
                          horizontal: MediaQuery.orientationOf(context) == Orientation.landscape ? 8 : 16,
                        ),
                        itemCount: _sales.length,
                        itemBuilder: (context, index) {
                          final s = _sales[index];
                          return Card(
                            margin: const EdgeInsets.only(bottom: 10),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
                            child: ListTile(
                              leading: CircleAvatar(
                                backgroundColor: colorScheme.primaryContainer,
                                child: Icon(Icons.receipt_rounded, color: colorScheme.onPrimaryContainer),
                              ),
                              title: Text(
                                '\$${s.totalAmount.toStringAsFixed(2)}',
                                style: TextStyle(fontWeight: FontWeight.w700, color: colorScheme.onSurface),
                              ),
                              subtitle: Text(
                                '${dateFormat.format(s.createdAt)} • ${s.sellerName ?? 'Unknown'}',
                                style: TextStyle(color: colorScheme.onSurfaceVariant, fontSize: 12),
                              ),
                              trailing: Icon(Icons.chevron_right_rounded, color: colorScheme.onSurfaceVariant),
                              onTap: () => _showSaleItems(context, s, colorScheme),
                            ),
                          );
                        },
                      ),
          ),
          if (_sales.isNotEmpty)
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: colorScheme.surfaceContainerHighest,
                borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('Total', style: TextStyle(fontWeight: FontWeight.w600, color: colorScheme.onSurface)),
                  Text(
                    '\$${_sales.fold<double>(0, (s, e) => s + e.totalAmount).toStringAsFixed(2)}',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800, color: colorScheme.primary),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }
}
