import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:http/http.dart' as http;
import 'package:supabase_flutter/supabase_flutter.dart';
import '../domain/sale_record_model.dart';
import '../data/sales_providers.dart';
import '../../auth/domain/profile_model.dart';
import '../../settings/presentation/settings_provider.dart';
import '../../../dashboard_provider.dart';
import '../../../core/money_format.dart';

class SalesHistoryPage extends ConsumerStatefulWidget {
  const SalesHistoryPage({super.key});

  @override
  ConsumerState<SalesHistoryPage> createState() => _SalesHistoryPageState();
}

class _SalesHistoryPageState extends ConsumerState<SalesHistoryPage> {
  DateTime? _startDate;
  DateTime? _endDate;
  String? _filterUserId;
  List<SaleRecordModel> _sales = [];
  List<ProfileModel> _users = [];
  bool _loading = true;
  bool _loadingUsers = true;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final role = ref.read(profileProvider).maybeWhen(
            data: (p) => p?.role.toLowerCase() ?? '',
            orElse: () => '',
          );
      if (role == 'cashier') {
        _filterUserId = Supabase.instance.client.auth.currentUser?.id;
      }
      _loadUsers();
      _loadSales();
    });
  }

  Future<void> _loadUsers() async {
    final role = ref.read(profileProvider).maybeWhen(
          data: (p) => p?.role.toLowerCase() ?? '',
          orElse: () => '',
        );
    if (role == 'cashier') {
      setState(() {
        _users = [];
        _loadingUsers = false;
      });
      return;
    }
    setState(() => _loadingUsers = true);
    try {
      final res = await Supabase.instance.client.from('profiles').select().order('full_name');
      setState(() {
        _users = (res as List).map((e) => ProfileModel.fromJson(Map<String, dynamic>.from(e))).toList();
        _loadingUsers = false;
      });
    } catch (_) {
      setState(() => _loadingUsers = false);
    }
  }

  Future<void> _loadSales() async {
    setState(() => _loading = true);
    try {
      final repo = ref.read(salesRepositoryProvider);
      final list = await repo.getSales(
        startDate: _startDate,
        endDate: _endDate,
        createdBy: _filterUserId,
      );
      setState(() {
        _sales = list;
        _loading = false;
      });
    } catch (_) {
      setState(() => _loading = false);
    }
  }

  Future<void> _exportPdf() async {
    final settings = await ref.read(settingsProvider.future);
    final profile = await ref.read(profileProvider.future);
    final generatorName = profile?.fullName ?? Supabase.instance.client.auth.currentUser?.email ?? 'System';
    final repo = ref.read(salesRepositoryProvider);
    final saleIds = _sales.map((s) => s.id).toList();
    final itemsBySale = await repo.getSaleItemsForSaleIds(saleIds);

    Uint8List? logoBytes;
    if (settings.logoUrl.isNotEmpty) {
      try {
        final res = await http.get(Uri.parse(settings.logoUrl));
        if (res.statusCode == 200) logoBytes = res.bodyBytes;
      } catch (_) {}
    }

    final doc = pw.Document();
    final dateFormat = DateFormat('yyyy-MM-dd HH:mm');
    final total = _sales.fold<double>(0, (s, e) => s + e.totalAmount);
    final periodText = 'Period: ${_startDate != null ? DateFormat('yyyy-MM-dd').format(_startDate!) : 'Any'} - ${_endDate != null ? DateFormat('yyyy-MM-dd').format(_endDate!) : 'Any'}';
    final isThermal = settings.printerType == 'thermal';
    final pageFormat = isThermal ? const PdfPageFormat(227, 800, marginAll: 12) : PdfPageFormat.a4;
    final logoH = isThermal ? 56.0 : 100.0;
    final logoW = isThermal ? 180.0 : 220.0;

    doc.addPage(
      pw.MultiPage(
        pageFormat: pageFormat,
        margin: isThermal ? const pw.EdgeInsets.all(12) : const pw.EdgeInsets.all(24),
        header: (context) => pw.SizedBox.shrink(),
        footer: (context) => pw.Padding(
          padding: const pw.EdgeInsets.only(top: 12),
          child: pw.Text(
            'Generated by $generatorName on ${dateFormat.format(DateTime.now())}',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
          ),
        ),
        build: (context) => [
          if (logoBytes != null)
            pw.Center(
              child: pw.Container(
                height: logoH,
                width: logoW,
                margin: const pw.EdgeInsets.only(bottom: 14),
                child: pw.Image(pw.MemoryImage(logoBytes), fit: pw.BoxFit.contain),
              ),
            ),
          pw.Center(
            child: pw.Column(
              mainAxisSize: pw.MainAxisSize.min,
              children: [
                pw.Text(
                  settings.shopName.isNotEmpty ? settings.shopName : 'Sales Report',
                  style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 4),
                if (settings.poBox.isNotEmpty)
                  pw.Text(
                    'P.O. Box: ${settings.poBox}',
                    style: const pw.TextStyle(fontSize: 9),
                    textAlign: pw.TextAlign.center,
                  ),
                if (settings.address.isNotEmpty)
                  pw.Text(
                    'Address: ${settings.address}',
                    style: const pw.TextStyle(fontSize: 9),
                    textAlign: pw.TextAlign.center,
                  ),
                if (settings.phoneNumber.isNotEmpty)
                  pw.Text(
                    'Tel: ${settings.phoneNumber}',
                    style: const pw.TextStyle(fontSize: 9),
                    textAlign: pw.TextAlign.center,
                  ),
              ],
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Text('Sales Report', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.Text(periodText, style: const pw.TextStyle(fontSize: 10)),
          pw.SizedBox(height: 12),
          pw.Text(
            'Products sold (by transaction)',
            style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: PdfColors.grey800),
          ),
          pw.SizedBox(height: 8),
          for (final sale in _sales) ...[
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey400, width: 0.5),
                borderRadius: pw.BorderRadius.circular(6),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    '${dateFormat.format(sale.createdAt)} • ${sale.sellerName ?? '-'} • ${formatKes(sale.totalAmount)}',
                    style: pw.TextStyle(
                      fontSize: isThermal ? 9.5 : 10.5,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 6),
                  ...(() {
                    final lines = itemsBySale[sale.id] ?? [];
                    if (lines.isEmpty) {
                      return [
                        pw.Text(
                          '— No line items',
                          style: pw.TextStyle(fontSize: 9, fontStyle: pw.FontStyle.italic, color: PdfColors.grey600),
                        ),
                      ];
                    }
                    return List<pw.Widget>.generate(lines.length, (i) {
                      final line = lines[i];
                      final n = i + 1;
                      return pw.Padding(
                        padding: const pw.EdgeInsets.only(top: 4),
                        child: pw.Row(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.SizedBox(
                              width: 24,
                              child: pw.Text('$n.', style: const pw.TextStyle(fontSize: 9.5)),
                            ),
                            pw.Expanded(
                              child: pw.Text(line.productName, style: const pw.TextStyle(fontSize: 10)),
                            ),
                            pw.Text('${line.quantity}×', style: const pw.TextStyle(fontSize: 9)),
                            pw.SizedBox(width: 6),
                            pw.Text(formatKes(line.totalPrice), style: const pw.TextStyle(fontSize: 9.5)),
                          ],
                        ),
                      );
                    });
                  })(),
                ],
              ),
            ),
            pw.SizedBox(height: 10),
          ],
          pw.SizedBox(height: 4),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              'Grand total: ${formatKes(total)}',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => doc.save(),
      name: 'Sales_Report_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.pdf',
    );
  }

  Future<void> _printReport() async {
    await _exportPdf();
  }

  Future<void> _showSaleItems(BuildContext context, SaleRecordModel sale, ColorScheme colorScheme) async {
    final repo = ref.read(salesRepositoryProvider);
    final items = await repo.getSaleItems(sale.id);
    if (!context.mounted) return;
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: colorScheme.surface,
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))),
      builder: (context) => DraggableScrollableSheet(
        initialChildSize: 0.6,
        minChildSize: 0.3,
        maxChildSize: 0.95,
        expand: false,
        builder: (context, scrollController) => Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const SizedBox(height: 8),
            Container(width: 40, height: 4, decoration: BoxDecoration(color: colorScheme.onSurfaceVariant.withAlpha(102), borderRadius: BorderRadius.circular(2))),
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 16, 20, 8),
              child: Row(
                children: [
                  Text('Products sold', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700, color: colorScheme.onSurface)),
                  const Spacer(),
                  Text(formatKes(sale.totalAmount), style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: colorScheme.primary)),
                ],
              ),
            ),
            Flexible(
              child: items.isEmpty
                  ? Center(child: Text('No line items recorded for this sale.', style: TextStyle(color: colorScheme.onSurfaceVariant)))
                  : ListView.builder(
                      controller: scrollController,
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 24),
                      itemCount: items.length,
                      itemBuilder: (context, index) {
                        final i = items[index];
                        return Padding(
                          padding: const EdgeInsets.only(bottom: 10),
                          child: Material(
                            color: colorScheme.surfaceContainerHighest.withAlpha(60),
                            borderRadius: BorderRadius.circular(14),
                            child: ListTile(
                              contentPadding: const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
                              leading: ClipRRect(
                                borderRadius: BorderRadius.circular(10),
                                child: i.imageUrl.isNotEmpty
                                    ? Image.network(
                                        i.imageUrl,
                                        width: 52,
                                        height: 52,
                                        fit: BoxFit.cover,
                                        errorBuilder: (_, __, ___) => Container(
                                          width: 52,
                                          height: 52,
                                          color: colorScheme.primaryContainer.withAlpha(80),
                                          child: Icon(Icons.inventory_2_rounded, color: colorScheme.primary, size: 26),
                                        ),
                                      )
                                    : Container(
                                        width: 52,
                                        height: 52,
                                        color: colorScheme.primaryContainer.withAlpha(80),
                                        child: Icon(Icons.inventory_2_rounded, color: colorScheme.primary, size: 26),
                                      ),
                              ),
                              title: Text(i.productName, style: TextStyle(fontWeight: FontWeight.w600, color: colorScheme.onSurface)),
                              subtitle: Text('Qty: ${i.quantity} × ${formatKes(i.unitPrice)}', style: TextStyle(color: colorScheme.onSurfaceVariant, fontSize: 12)),
                              trailing: Text(formatKes(i.totalPrice), style: TextStyle(fontWeight: FontWeight.w700, color: colorScheme.primary)),
                            ),
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final dateFormat = DateFormat('MMM d, y HH:mm');

    return Scaffold(
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Text('Sales History', style: TextStyle(fontWeight: FontWeight.w700, color: colorScheme.onSurface)),
        leading: IconButton(
          icon: Icon(Icons.arrow_back_rounded, color: colorScheme.onSurface),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          if (_sales.isNotEmpty) ...[
            IconButton(
              icon: Icon(Icons.picture_as_pdf_rounded, color: colorScheme.primary),
              onPressed: _exportPdf,
              tooltip: 'Export PDF',
            ),
            IconButton(
              icon: Icon(Icons.print_rounded, color: colorScheme.primary),
              onPressed: _printReport,
              tooltip: 'Print',
            ),
          ],
        ],
      ),
      body: Column(
        children: [
          // Filters — responsive padding for landscape
          Padding(
            padding: EdgeInsets.fromLTRB(
              MediaQuery.orientationOf(context) == Orientation.landscape ? 8 : 16,
              12,
              MediaQuery.orientationOf(context) == Orientation.landscape ? 8 : 16,
              8,
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Expanded(
                      child: OutlinedButton.icon(
                        onPressed: () async {
                          final date = await showDatePicker(
                            context: context,
                            initialDate: _startDate ?? DateTime.now(),
                            firstDate: DateTime(2020),
                            lastDate: DateTime.now(),
                          );
                          if (date != null) setState(() => _startDate = date);
                          _loadSales();
                        },
                        icon: const Icon(Icons.calendar_today_rounded, size: 18),
                        label: Text(_startDate != null ? DateFormat('MMM d').format(_startDate!) : 'Start'),
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: OutlinedButton.icon(
                        onPressed: () async {
                          final date = await showDatePicker(
                            context: context,
                            initialDate: _endDate ?? DateTime.now(),
                            firstDate: _startDate ?? DateTime(2020),
                            lastDate: DateTime.now(),
                          );
                          if (date != null) setState(() => _endDate = date);
                          _loadSales();
                        },
                        icon: const Icon(Icons.calendar_today_rounded, size: 18),
                        label: Text(_endDate != null ? DateFormat('MMM d').format(_endDate!) : 'End'),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                if (_loadingUsers)
                  const SizedBox(height: 40, child: Center(child: CircularProgressIndicator(strokeWidth: 2)))
                else
                  DropdownButtonFormField<String?>(
                    value: _filterUserId,
                    decoration: InputDecoration(
                      labelText: 'Filter by user',
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                      isDense: true,
                    ),
                    items: [
                      const DropdownMenuItem(value: null, child: Text('All users')),
                      ..._users.map(
                        (u) => DropdownMenuItem(
                          value: u.id,
                          child: Text('${u.fullName} (${u.role})'),
                        ),
                      ),
                    ],
                    onChanged: (v) {
                      setState(() => _filterUserId = v);
                      _loadSales();
                    },
                  ),
              ],
            ),
          ),
          // List
          Expanded(
            child: _loading
                ? Center(child: CircularProgressIndicator(color: colorScheme.primary))
                : _sales.isEmpty
                    ? Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(Icons.receipt_long_rounded, size: 64, color: colorScheme.onSurfaceVariant.withAlpha(120)),
                            const SizedBox(height: 16),
                            Text(
                              'No sales in this period',
                              style: TextStyle(color: colorScheme.onSurfaceVariant, fontSize: 16),
                            ),
                          ],
                        ),
                      )
                    : ListView.builder(
                        padding: EdgeInsets.symmetric(
                          horizontal: MediaQuery.orientationOf(context) == Orientation.landscape ? 8 : 16,
                        ),
                        itemCount: _sales.length,
                        itemBuilder: (context, index) {
                          final s = _sales[index];
                          return Container(
                            margin: const EdgeInsets.only(bottom: 12),
                            decoration: BoxDecoration(
                              color: colorScheme.surfaceContainerHighest.withAlpha(100),
                              borderRadius: BorderRadius.circular(20),
                              border: Border.all(color: colorScheme.outline.withAlpha(40)),
                              boxShadow: [
                                BoxShadow(
                                  color: colorScheme.shadow.withAlpha(20),
                                  blurRadius: 12,
                                  offset: const Offset(0, 3),
                                ),
                              ],
                            ),
                            child: InkWell(
                              onTap: () => _showSaleItems(context, s, colorScheme),
                              borderRadius: BorderRadius.circular(20),
                              child: Padding(
                                padding: const EdgeInsets.all(16),
                                child: Row(
                                  children: [
                                    Container(
                                      width: 50,
                                      height: 50,
                                      decoration: BoxDecoration(
                                        gradient: LinearGradient(
                                          colors: [
                                            colorScheme.primary.withAlpha(50),
                                            colorScheme.primary.withAlpha(20),
                                          ],
                                        ),
                                        borderRadius: BorderRadius.circular(16),
                                      ),
                                      child: Icon(Icons.receipt_rounded, color: colorScheme.primary, size: 24),
                                    ),
                                    const SizedBox(width: 14),
                                    Expanded(
                                      child: Column(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            formatKes(s.totalAmount),
                                            style: TextStyle(
                                              fontWeight: FontWeight.w800,
                                              fontSize: 16,
                                              color: colorScheme.onSurface,
                                              letterSpacing: -0.3,
                                            ),
                                          ),
                                          const SizedBox(height: 3),
                                          Text(
                                            '${dateFormat.format(s.createdAt)} • ${s.sellerName ?? 'Unknown'}',
                                            style: TextStyle(
                                              color: colorScheme.onSurfaceVariant,
                                              fontSize: 12,
                                              fontWeight: FontWeight.w500,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      padding: const EdgeInsets.all(8),
                                      decoration: BoxDecoration(
                                        color: colorScheme.primary.withAlpha(15),
                                        borderRadius: BorderRadius.circular(10),
                                      ),
                                      child: Icon(
                                        Icons.chevron_right_rounded,
                                        color: colorScheme.primary,
                                        size: 18,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          );
                        },
                      ),
          ),
          if (_sales.isNotEmpty)
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [
                    colorScheme.primary.withAlpha(20),
                    colorScheme.primary.withAlpha(8),
                  ],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
                borderRadius: const BorderRadius.vertical(top: Radius.circular(24)),
                border: Border(
                  top: BorderSide(color: colorScheme.primary.withAlpha(40), width: 1),
                ),
              ),
              child: SafeArea(
                top: false,
                child: Row(
                  children: [
                    Container(
                      width: 44,
                      height: 44,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          colors: [
                            colorScheme.primary.withAlpha(60),
                            colorScheme.primary.withAlpha(30),
                          ],
                        ),
                        borderRadius: BorderRadius.circular(14),
                      ),
                      child: Icon(Icons.account_balance_wallet_rounded, color: colorScheme.primary, size: 22),
                    ),
                    const SizedBox(width: 14),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Total Revenue',
                            style: TextStyle(
                              fontWeight: FontWeight.w600,
                              fontSize: 12,
                              color: colorScheme.onSurfaceVariant,
                            ),
                          ),
                          Text(
                            formatKes(_sales.fold<double>(0, (s, e) => s + e.totalAmount)),
                            style: TextStyle(
                              fontSize: 20,
                              fontWeight: FontWeight.w900,
                              color: colorScheme.primary,
                              letterSpacing: -0.5,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Text(
                      '${_sales.length} sale${_sales.length == 1 ? '' : 's'}',
                      style: TextStyle(
                        color: colorScheme.onSurfaceVariant,
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }
}
